[build]
  command = "npm run build:netlify"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_KEYS = "OPENAI_API_KEY,GEMINI_API_KEY,CLERK_SECRET_KEY,NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
  SECRETS_SCAN_OMIT_PATHS = "app/api/**,NETLIFY_DEPLOYMENT.md,SETUP_INSTRUCTIONS.md"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
